apiVersion: apps/v1
kind: Deployment
metadata:
  name: APP_NAME
  labels:
    app: APP_NAME
    version: "CI_COMMIT_SHORT_SHA"
spec:
  replicas: APP_REPLICAS
  selector:
    matchLabels:
      app: APP_NAME
  template:
    metadata:
      labels:
        app: APP_NAME
        version: "CI_COMMIT_SHORT_SHA"
    spec:
      imagePullSecrets:
      - name: aliyun-registry
      containers:
      - name: APP_NAME
        image: APP_IMAGE
        ports:
        - containerPort: 9097
        readinessProbe:
          httpGet:
            path: /
            port: 9097
          initialDelaySeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: APP_NAME
  labels:
    app: APP_NAME
spec:
  ports:
  - port: 9097
    name: http
  selector:
    app: APP_NAME